stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - data/raw/weatherAUS.csv
      - src/prepare.py
      - conf/config.yaml
    outs:
      - data/processed:
          cache: true

  train:
    cmd: python src/train.py model=random_forest
    deps:
      - data/processed
      - src/train.py
      - conf/config.yaml
      - conf/model/random_forest.yaml
    outs:
      - model.pkl:
          cache: true
    metrics:
      - metrics.json:
          cache: false
    plots:
      - confusion_matrix.png:
          cache: false

  optimize:
    cmd: python src/train.py --hpo model=random_forest model_path=optimized_model.pkl
    deps:
      - data/processed
      - src/train.py
      - conf/config.yaml
      - conf/model/random_forest.yaml
    outs:
      - optimized_model.pkl:
          cache: true
